version: '3'
services:
  mysqldbserver:
    image: mysql
    container_name: userdb
    environment:
      - MYSQL_ROOT_PASSWORD=userdb
      - MYSQL_DATABASE=userdb

    ports:
      - "3307:3306"
    volumes:
      - /data/mysql

  ms:
    restart: on-failure
    container_name: ms-user
    build:
      context: .
      dockerfile: Dockerfile
    image: ms-user:latest
    expose:
      - "8085"
    ports:
      - "8085:8085"
    depends_on:
      - mysqldbserver