# This is a basic workflow to help you get started with Actions

name: Deploy with docker

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.2
      - name: Set up JDK 17
        uses: actions/setup-java@v3.5.0
        with:
          java-version: '17'
          distribution: 'corretto'
      - name: Dependies Cache
        uses: actions/cache@v3.0.8
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build with Maven
        run: mvn package -Dmaven.test.skip=true
      - name: Docker Login
        uses: docker/login-action@v2.0.0
        with:
    # Username used to log against the Docker registry
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
    # Password or personal access token used to log against the Docker registry
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2.0.0
      - name: Build and push Docker images
        uses: docker/build-push-action@v3.1.1
        with:
    # Build's context is the set of files located in the specified PATH or URL
          context: ./
    # Path to the Dockerfile
          file: ./Dockerfile
    # Push is a shorthand for --output=type=registry
          push: true
    # List of tags
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/myimage:latest
        
